from workflow.state import ResearchState
from templates.report_template import render_html_report


async def render_html_node(state: ResearchState) -> dict:
    """Node 4: Convert Markdown report to HTML using the warm-brown + gold template."""
    industry = state["industry"]
    markdown_text = state.get("markdown_report", "")

    html = render_html_report(
        markdown_text=markdown_text,
        title=f"{industry}行业研究报告",
        industry=industry,
        subtitle="LangGraph 自动生成 · 仅供参考，不构成投资建议",
        byline="Generated by Industry Research App",
    )

    return {
        "html_report": html,
        "progress": 100,
        "status_message": "报告生成完成",
        "error": None,
    }
